apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: arm64-class
spec:
  instanceProfile: karpenter-node-instance-profile
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet
  amiFamily: AL2
  amiSelectorTerms:
    - ssmParameter: /aws/service/eks/optimized-ami/1.32/amazon-linux-2-arm64/recommended/image_id
